In [2]:
import pandas as pd
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository.csv")
print(df)

            country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100  2024-05-16 09:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100  2024-05-16 09:45                 26.0
...                    ...               ...                  ...
135068          1775975400  2026-04-12 02:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400  2026-04-12 09:30                 19.3
135071          1775975400  2026-04-12 08:30                 18.5
135072          1775975400  2026-04-12 08:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise  sunset  moonrise  moonset       moon_phase  moon_illumination
0         04:50   18:50     12:12    01:11   Waxing Gibbous                 55
1         05:21   19:54     12:58    02:14   Waxing Gibbous                 55
2         05:40   19:50     13:15    02:14   Waxing Gibbous                 55
3         06:31   21:11     14:12    03:31   Waxing Gibbous                 55
4         06:12   17:55     13:17    00:38   Waxing Gibbous                 55
...         ...     ...       ...      ...              ...                ...
135068    06:18   18:38     02:36    14:31  Waning Crescent                 31
135069    05:41   18:14     02:02    13:21  Waning Crescent                 35
135070    05:51   18:17     02:06    13:45  Waning Crescent                 34
135071    06:14   18:01     01:26    14:30  Waning Crescent                 33
135072    06:04   17:49     01:10    14:22  Waning Crescent                 33

[135073 rows x 41 columns]

#head

first five rows of this data

In [3]:
df.head

<bound method NDFrame.head of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100  2024-05-16 09:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100  2024-05-16 09:45                 26.0
...                    ...               ...                  ...
135068          1775975400  2026-04-12 02:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400  2026-04-12 09:30                 19.3
135071          1775975400  2026-04-12 08:30                 18.5
135072          1775975400  2026-04-12 08:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise  sunset  moonrise  moonset       moon_phase  moon_illumination
0         04:50   18:50     12:12    01:11   Waxing Gibbous                 55
1         05:21   19:54     12:58    02:14   Waxing Gibbous                 55
2         05:40   19:50     13:15    02:14   Waxing Gibbous                 55
3         06:31   21:11     14:12    03:31   Waxing Gibbous                 55
4         06:12   17:55     13:17    00:38   Waxing Gibbous                 55
...         ...     ...       ...      ...              ...                ...
135068    06:18   18:38     02:36    14:31  Waning Crescent                 31
135069    05:41   18:14     02:02    13:21  Waning Crescent                 35
135070    05:51   18:17     02:06    13:45  Waning Crescent                 34
135071    06:14   18:01     01:26    14:30  Waning Crescent                 33
135072    06:04   17:49     01:10    14:22  Waning Crescent                 33

[135073 rows x 41 columns]>

#tail

last five rows of this data

In [4]:
df.tail

<bound method NDFrame.tail of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100  2024-05-16 09:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100  2024-05-16 09:45                 26.0
...                    ...               ...                  ...
135068          1775975400  2026-04-12 02:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400  2026-04-12 09:30                 19.3
135071          1775975400  2026-04-12 08:30                 18.5
135072          1775975400  2026-04-12 08:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise  sunset  moonrise  moonset       moon_phase  moon_illumination
0         04:50   18:50     12:12    01:11   Waxing Gibbous                 55
1         05:21   19:54     12:58    02:14   Waxing Gibbous                 55
2         05:40   19:50     13:15    02:14   Waxing Gibbous                 55
3         06:31   21:11     14:12    03:31   Waxing Gibbous                 55
4         06:12   17:55     13:17    00:38   Waxing Gibbous                 55
...         ...     ...       ...      ...              ...                ...
135068    06:18   18:38     02:36    14:31  Waning Crescent                 31
135069    05:41   18:14     02:02    13:21  Waning Crescent                 35
135070    05:51   18:17     02:06    13:45  Waning Crescent                 34
135071    06:14   18:01     01:26    14:30  Waning Crescent                 33
135072    06:04   17:49     01:10    14:22  Waning Crescent                 33

[135073 rows x 41 columns]>

#sample

selecting seven random rows

In [6]:
df.sample(7)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
1618,Gambia,Banjul,13.4500,-16.5800,Africa/Banjul,1716472800,2024-05-23 14:00,32.0,89.6,Sunny,...,31.700,117.100,2,3,06:39,19:28,19:39,06:19,Full Moon,100
25711,Lithuania,Vilnius,54.6800,25.3200,Europe/Vilnius,1727343000,2024-09-26 12:30,19.3,66.7,Partly cloudy,...,10.360,12.025,1,1,07:12,19:07,No moonrise,17:42,Waning Crescent,37
130290,Indonesia,Laos,-8.1826,114.3188,Asia/Jakarta,1773901800,2026-03-19 13:30,29.6,85.3,Patchy rain nearby,...,20.050,20.450,2,2,05:27,17:34,05:23,17:43,New Moon,0
87898,Belarus,Minsk,53.9000,27.5667,Europe/Minsk,1754986500,2025-08-12 11:15,18.3,64.9,Partly cloudy,...,9.620,16.835,1,1,05:43,20:45,21:42,09:34,Waning Gibbous,92
123763,Belize,Belmopan,17.2500,-88.7667,America/Belize,1770965100,2026-02-13 00:45,18.4,65.1,Fog,...,5.150,6.650,1,1,06:22,17:56,03:32,14:39,Waning Crescent,18
89568,Niger,Niamey,13.5167,2.1167,Africa/Niamey,1755681300,2025-08-20 10:15,28.2,82.8,Sunny,...,5.365,9.805,1,1,06:39,19:10,03:52,17:15,Waning Crescent,12
18283,Iraq,Baghdad,33.3400,44.3900,Asia/Baghdad,1724070600,2024-08-19 15:30,46.4,115.5,Sunny,...,16.400,39.900,2,2,05:28,18:43,18:49,04:38,Full Moon,99

#shape

total number of rows and columns

In [7]:
df.shape

(135073, 41)

#info

information about entire data

In [8]:
df.info

<bound method DataFrame.info of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
135068    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
135069      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
135070        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
135071       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
135072     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100  2024-05-16 09:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100  2024-05-16 09:45                 26.0
...                    ...               ...                  ...
135068          1775975400  2026-04-12 02:30                 19.1
135069          1775975400  2026-04-12 13:30                 34.2
135070          1775975400  2026-04-12 09:30                 19.3
135071          1775975400  2026-04-12 08:30                 18.5
135072          1775975400  2026-04-12 08:30                 17.4

        temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                         79.8  Partly Cloudy  ...               8.40
1                         66.2  Partly cloudy  ...               1.10
2                         73.4          Sunny  ...              10.40
3                         43.3  Light drizzle  ...               0.70
4                         78.8  Partly cloudy  ...             183.40
...                        ...            ...  ...                ...
135068                    66.3  Partly Cloudy  ...              16.35
135069                    93.6          Sunny  ...              61.15
135070                    66.7          Sunny  ...               7.45
135071                    65.3          Sunny  ...               5.45
135072                    63.3          Sunny  ...              19.85

        air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0                  26.60                         1                          1
1                   2.00                         1                          1
2                  18.40                         1                          1
3                   0.90                         1                          1
4                 262.30                         5                         10
...                  ...                       ...                        ...
135068             18.15                         2                          2
135069             64.45                         3                          8
135070             15.35                         1                          1
135071              6.15                         1                          1
135072             20.55                         2                          2

        sunrise  sunset  moonrise  moonset       moon_phase  moon_illumination
0         04:50   18:50     12:12    01:11   Waxing Gibbous                 55
1         05:21   19:54     12:58    02:14   Waxing Gibbous                 55
2         05:40   19:50     13:15    02:14   Waxing Gibbous                 55
3         06:31   21:11     14:12    03:31   Waxing Gibbous                 55
4         06:12   17:55     13:17    00:38   Waxing Gibbous                 55
...         ...     ...       ...      ...              ...                ...
135068    06:18   18:38     02:36    14:31  Waning Crescent                 31
135069    05:41   18:14     02:02    13:21  Waning Crescent                 35
135070    05:51   18:17     02:06    13:45  Waning Crescent                 34
135071    06:14   18:01     01:26    14:30  Waning Crescent                 33
135072    06:04   17:49     01:10    14:22  Waning Crescent                 33

[135073 rows x 41 columns]>

#columns

all columns of this data

In [9]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

#dtypes

default data type

In [10]:
df.dtypes

country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                       int64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                  int64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

#iloc

In [11]:
df.iloc[3]

country                                  Andorra
location_name                   Andorra La Vella
latitude                                    42.5
longitude                                   1.52
timezone                          Europe/Andorra
last_updated_epoch                    1715849100
last_updated                    2024-05-16 10:45
temperature_celsius                          6.3
temperature_fahrenheit                      43.3
condition_text                     Light drizzle
wind_mph                                     7.4
wind_kph                                    11.9
wind_degree                                  215
wind_direction                                SW
pressure_mb                                 1007
pressure_in                                29.75
precip_mm                                    0.3
precip_in                                   0.01
humidity                                      61
cloud                                        100
feels_like_celsius                           3.8
feels_like_fahrenheit                       38.9
visibility_km                                2.0
visibility_miles                               1
uv_index                                     2.0
gust_mph                                     8.5
gust_kph                                    13.7
air_quality_Carbon_Monoxide                170.2
air_quality_Ozone                           64.4
air_quality_Nitrogen_dioxide                 1.6
air_quality_Sulphur_dioxide                  0.2
air_quality_PM2.5                            0.7
air_quality_PM10                             0.9
air_quality_us-epa-index                       1
air_quality_gb-defra-index                     1
sunrise                                    06:31
sunset                                     21:11
moonrise                                   14:12
moonset                                    03:31
moon_phase                        Waxing Gibbous
moon_illumination                             55
Name: 3, dtype: object

In [12]:
len(df["moon_illumination"]>10)

135073

In [13]:
df["timezone"].str.split("/")

0              [Asia, Kabul]
1           [Europe, Tirane]
2          [Africa, Algiers]
3          [Europe, Andorra]
4           [Africa, Luanda]
                 ...
135068    [America, Caracas]
135069       [Asia, Bangkok]
135070          [Asia, Aden]
135071      [Africa, Lusaka]
135072      [Africa, Harare]
Name: timezone, Length: 135073, dtype: object

In [14]:
df["moon_illumination"].mean()

np.float64(49.98644436712)

In [15]:
df["moon_illumination"].max()

100

In [16]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.sort_values(by="temperature_celsius")

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
118990,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768719600,2026-01-18 15:00,-29.8,-21.6,Mist,...,9.15,9.350,1,1,08:35,17:31,08:39,16:36,Waning Crescent,1
119182,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768893300,2026-01-20 15:15,-28.9,-20.0,Sunny,...,59.45,60.650,3,8,08:33,17:34,09:33,19:04,Waxing Crescent,1
121617,Belarus,Minsk,53.9000,27.5667,Europe/Minsk,1770015600,2026-02-02 10:00,-26.9,-16.4,Freezing fog,...,10.35,14.950,1,1,08:55,17:53,18:36,09:24,Waning Gibbous,100
118606,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768547700,2026-01-16 15:15,-26.8,-16.2,Mist,...,14.25,14.950,1,2,08:36,17:28,07:09,14:30,Waning Crescent,9
118801,Mongolia,Ulaanbaatar,47.9167,106.9167,Asia/Ulaanbaatar,1768633200,2026-01-17 15:00,-25.9,-14.6,Partly cloudy,...,17.05,17.350,2,2,08:36,17:30,07:59,15:29,Waning Crescent,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85049,Kuwait,Kuwait City,29.3667,47.9600,Asia/Kuwait,1753691400,2025-07-28 11:30,48.8,119.8,Sunny,...,100.64,503.015,4,10,05:06,18:43,08:26,21:03,Waxing Crescent,11
8425,Kuwait,Kuwait City,29.3700,47.9600,Asia/Kuwait,1719494100,2024-06-27 16:15,48.9,120.0,Sunny,...,29.00,133.500,2,3,04:51,18:52,23:08,10:13,Waning Gibbous,71
11145,Iraq,Baghdad,33.3400,44.3900,Asia/Baghdad,1720701900,2024-07-11 15:45,49.1,120.3,Sunny,...,12.30,39.500,1,2,05:02,19:14,09:58,22:37,Waxing Crescent,23
7460,Iraq,Baghdad,33.3400,44.3900,Asia/Baghdad,1719063900,2024-06-22 16:45,49.1,120.4,Partly cloudy,...,16.10,47.900,2,2,04:54,19:16,20:06,04:42,Full Moon,100
6896,Kuwait,Kuwait City,29.3700,47.9600,Asia/Kuwait,1718804700,2024-06-19 16:45,49.2,120.6,Sunny,...,33.60,187.000,2,3,04:49,18:50,16:33,02:17,Waxing Gibbous,90

In [19]:
df["timezone"]=df["timezone"].str.replace("+","")

In [20]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

In [21]:
df['continent']=df["timezone"].str.split('/').str[0]

In [22]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33,Africa

In [29]:
df['last_updated']=pd.to_datetime(df['last_updated'])

In [30]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33,Africa

In [31]:
df['location_name']=df['location_name'].str.strip()

In [32]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33,Africa

#head

first five rows of this data

In [33]:
print(df.head())

       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch        last_updated  temperature_celsius  \
0          1715849100 2024-05-16 13:15:00                 26.6
1          1715849100 2024-05-16 10:45:00                 19.0
2          1715849100 2024-05-16 09:45:00                 23.0
3          1715849100 2024-05-16 10:45:00                  6.3
4          1715849100 2024-05-16 09:45:00                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_PM10  \
0                    79.8  Partly Cloudy  ...              26.6
1                    66.2  Partly cloudy  ...               2.0
2                    73.4          Sunny  ...              18.4
3                    43.3  Light drizzle  ...               0.9
4                    78.8  Partly cloudy  ...             262.3

   air_quality_us-epa-index  air_quality_gb-defra-index sunrise  sunset  \
0                         1                           1   04:50   18:50
1                         1                           1   05:21   19:54
2                         1                           1   05:40   19:50
3                         1                           1   06:31   21:11
4                         5                          10   06:12   17:55

   moonrise  moonset      moon_phase  moon_illumination  continent
0     12:12    01:11  Waxing Gibbous                 55       Asia
1     12:58    02:14  Waxing Gibbous                 55     Europe
2     13:15    02:14  Waxing Gibbous                 55     Africa
3     14:12    03:31  Waxing Gibbous                 55     Europe
4     13:17    00:38  Waxing Gibbous                 55     Africa

[5 rows x 42 columns]

In [34]:
df['latitude']=pd.to_numeric(df['latitude'],errors='coerce')

In [35]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33,Africa

In [40]:
df['longitude']=pd.to_numeric(df['longitude'],errors='coerce')

In [41]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,Asia
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,Europe
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,Africa
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,Europe
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31,America
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35,Asia
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34,Asia
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33,Africa
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33,Africa

In [39]:
df.describe()

,latitude,longitude,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,135073.000000,135073.000000,1.350730e+05,135073,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,...,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000,135073.000000
mean,19.208948,21.961711,1.745908e+09,2025-04-29 08:31:05.284698112,21.283607,70.312259,8.021764,12.913410,168.894909,1014.069244,...,18.264350,461.415911,58.100332,15.007413,10.365922,24.211112,48.433111,1.699200,2.605791,49.986444
min,-41.300000,-175.200000,1.715849e+09,2024-05-16 01:45:00,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,4.050300,-6.836100,1.730970e+09,2024-11-07 05:00:00,16.000000,60.800000,3.800000,6.100000,80.000000,1010.000000,...,10.300000,203.500000,38.000000,1.665000,1.110000,7.050000,9.990000,1.000000,1.000000,15.000000
50%,17.250000,23.236100,1.745916e+09,2025-04-29 10:45:00,24.000000,75.200000,6.700000,10.800000,161.000000,1014.000000,...,15.300000,294.150000,55.000000,5.550000,2.405000,14.200000,19.980000,1.000000,2.000000,50.000000
75%,40.400000,49.882200,1.760860e+09,2025-10-19 13:45:00,28.000000,82.400000,11.000000,17.600000,256.000000,1018.000000,...,24.200000,460.650000,74.000000,17.390000,8.325000,27.750000,41.450000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.775975e+09,2026-04-12 19:30:00,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000
std,24.416748,65.787645,1.734686e+07,NaN,9.699084,17.458216,7.225402,11.624983,103.706143,10.369057,...,13.829708,758.835655,30.777578,23.723174,35.691840,36.911798,149.473695,0.941003,2.445307,35.022525

In [47]:
df['time']=df['last_updated'].dt.time

In [48]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,time,date
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,Asia,13:15:00,2024-05-16
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,2,06:18,18:38,02:36,14:31,Waning Crescent,31,America,02:30:00,2026-04-12
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,8,05:41,18:14,02:02,13:21,Waning Crescent,35,Asia,13:30:00,2026-04-12
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,1,05:51,18:17,02:06,13:45,Waning Crescent,34,Asia,09:30:00,2026-04-12
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,1,06:14,18:01,01:26,14:30,Waning Crescent,33,Africa,08:30:00,2026-04-12
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,2,06:04,17:49,01:10,14:22,Waning Crescent,33,Africa,08:30:00,2026-04-12

In [45]:
df['date']=df['last_updated'].dt.date

In [49]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,time,date
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55,Asia,13:15:00,2024-05-16
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,2,06:18,18:38,02:36,14:31,Waning Crescent,31,America,02:30:00,2026-04-12
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,8,05:41,18:14,02:02,13:21,Waning Crescent,35,Asia,13:30:00,2026-04-12
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,1,05:51,18:17,02:06,13:45,Waning Crescent,34,Asia,09:30:00,2026-04-12
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,1,06:14,18:01,01:26,14:30,Waning Crescent,33,Africa,08:30:00,2026-04-12
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,2,06:04,17:49,01:10,14:22,Waning Crescent,33,Africa,08:30:00,2026-04-12

In [53]:
df['timezone']=df['timezone'].fillna('unknown/unknown')

In [54]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,time,date
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,partly cloudy,...,1,2026-04-22 04:50:00,18:50,12:12,01:11,Waxing Gibbous,55,Asia,13:15:00,2024-05-16
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,partly cloudy,...,1,2026-04-22 05:21:00,19:54,12:58,02:14,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,sunny,...,1,2026-04-22 05:40:00,19:50,13:15,02:14,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,light drizzle,...,1,2026-04-22 06:31:00,21:11,14:12,03:31,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,partly cloudy,...,10,2026-04-22 06:12:00,17:55,13:17,00:38,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,partly cloudy,...,2,2026-04-22 06:18:00,18:38,02:36,14:31,Waning Crescent,31,America,02:30:00,2026-04-12
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,sunny,...,8,2026-04-22 05:41:00,18:14,02:02,13:21,Waning Crescent,35,Asia,13:30:00,2026-04-12
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,sunny,...,1,2026-04-22 05:51:00,18:17,02:06,13:45,Waning Crescent,34,Asia,09:30:00,2026-04-12
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,sunny,...,1,2026-04-22 06:14:00,18:01,01:26,14:30,Waning Crescent,33,Africa,08:30:00,2026-04-12
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,sunny,...,2,2026-04-22 06:04:00,17:49,01:10,14:22,Waning Crescent,33,Africa,08:30:00,2026-04-12

In [56]:
split_columns=df['timezone'].str.split('/',n=1,expand=True)

In [57]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,time,date
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,partly cloudy,...,1,2026-04-22 04:50:00,18:50,12:12,01:11,Waxing Gibbous,55,Asia,13:15:00,2024-05-16
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,partly cloudy,...,1,2026-04-22 05:21:00,19:54,12:58,02:14,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,sunny,...,1,2026-04-22 05:40:00,19:50,13:15,02:14,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,light drizzle,...,1,2026-04-22 06:31:00,21:11,14:12,03:31,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,partly cloudy,...,10,2026-04-22 06:12:00,17:55,13:17,00:38,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,partly cloudy,...,2,2026-04-22 06:18:00,18:38,02:36,14:31,Waning Crescent,31,America,02:30:00,2026-04-12
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,sunny,...,8,2026-04-22 05:41:00,18:14,02:02,13:21,Waning Crescent,35,Asia,13:30:00,2026-04-12
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,sunny,...,1,2026-04-22 05:51:00,18:17,02:06,13:45,Waning Crescent,34,Asia,09:30:00,2026-04-12
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,sunny,...,1,2026-04-22 06:14:00,18:01,01:26,14:30,Waning Crescent,33,Africa,08:30:00,2026-04-12
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,sunny,...,2,2026-04-22 06:04:00,17:49,01:10,14:22,Waning Crescent,33,Africa,08:30:00,2026-04-12

In [58]:
df['continent']=split_columns[0]

In [59]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,time,date
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,partly cloudy,...,1,2026-04-22 04:50:00,18:50,12:12,01:11,Waxing Gibbous,55,Asia,13:15:00,2024-05-16
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,partly cloudy,...,1,2026-04-22 05:21:00,19:54,12:58,02:14,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,sunny,...,1,2026-04-22 05:40:00,19:50,13:15,02:14,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,light drizzle,...,1,2026-04-22 06:31:00,21:11,14:12,03:31,Waxing Gibbous,55,Europe,10:45:00,2024-05-16
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,partly cloudy,...,10,2026-04-22 06:12:00,17:55,13:17,00:38,Waxing Gibbous,55,Africa,09:45:00,2024-05-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,partly cloudy,...,2,2026-04-22 06:18:00,18:38,02:36,14:31,Waning Crescent,31,America,02:30:00,2026-04-12
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,sunny,...,8,2026-04-22 05:41:00,18:14,02:02,13:21,Waning Crescent,35,Asia,13:30:00,2026-04-12
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,sunny,...,1,2026-04-22 05:51:00,18:17,02:06,13:45,Waning Crescent,34,Asia,09:30:00,2026-04-12
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,sunny,...,1,2026-04-22 06:14:00,18:01,01:26,14:30,Waning Crescent,33,Africa,08:30:00,2026-04-12
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,sunny,...,2,2026-04-22 06:04:00,17:49,01:10,14:22,Waning Crescent,33,Africa,08:30:00,2026-04-12

In [60]:
df['city']=split_columns[1]

In [61]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,continent,time,date,city
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,partly cloudy,...,2026-04-22 04:50:00,18:50,12:12,01:11,Waxing Gibbous,55,Asia,13:15:00,2024-05-16,Kabul
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,partly cloudy,...,2026-04-22 05:21:00,19:54,12:58,02:14,Waxing Gibbous,55,Europe,10:45:00,2024-05-16,Tirane
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,sunny,...,2026-04-22 05:40:00,19:50,13:15,02:14,Waxing Gibbous,55,Africa,09:45:00,2024-05-16,Algiers
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,light drizzle,...,2026-04-22 06:31:00,21:11,14:12,03:31,Waxing Gibbous,55,Europe,10:45:00,2024-05-16,Andorra
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,partly cloudy,...,2026-04-22 06:12:00,17:55,13:17,00:38,Waxing Gibbous,55,Africa,09:45:00,2024-05-16,Luanda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,partly cloudy,...,2026-04-22 06:18:00,18:38,02:36,14:31,Waning Crescent,31,America,02:30:00,2026-04-12,Caracas
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,sunny,...,2026-04-22 05:41:00,18:14,02:02,13:21,Waning Crescent,35,Asia,13:30:00,2026-04-12,Bangkok
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,sunny,...,2026-04-22 05:51:00,18:17,02:06,13:45,Waning Crescent,34,Asia,09:30:00,2026-04-12,Aden
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,sunny,...,2026-04-22 06:14:00,18:01,01:26,14:30,Waning Crescent,33,Africa,08:30:00,2026-04-12,Lusaka
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,sunny,...,2026-04-22 06:04:00,17:49,01:10,14:22,Waning Crescent,33,Africa,08:30:00,2026-04-12,Harare